# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
---

version: "2"

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile.build

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      BASE_GATEWAY_HTTP_URL: http://localhost:8888
      BASE_GATEWAY_WS_URL: ws://localhost:8888

