# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM alpine:latest AS runtime

RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

WORKDIR /app
COPY --from=go_client_example_build /src/jupyter-kernel-cli-go ./

ENTRYPOINT ["./jupyter-kernel-cli-go"]
